server:
  port: 8003

spring:
  #服务名
  application:
    name: service-vod

  profiles:
    active: dev
   #文件上传大小
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

  cloud:
    #nacos配置
    nacos:
      discovery:
        server-addr: localhost:8848

aliyun:
  vod:
    file:
      keyid: LTAI5tMPmnRuSjU3wmEC13TH
      keysecret: 60w1Stbt3qSUw6ABilXLeCvSWuFw10


