server:
  port: 8003

spring:
  application:
    name: service-vod
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

aliyun:
  vod:
    file:
      keyid: LTAI5tMPmnRuSjU3wmEC13TH
      keysecret: 60w1Stbt3qSUw6ABilXLeCvSWuFw10


