#服务端口号
server:
  port: 8004

spring:
  #服务名
  application:
    name: service-cms
  #数据库连接
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli?serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  redis:
    host: 192.168.217.4
    port: 6379
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-wait: -1
        max-active: 20
        max-idle: 5
        min-idle: 0



mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
