#服务端口
server:
  port: 8001

spring:
  #环境设置：dev、test、prod
  profiles:
    active: dev


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli?serverTimezone=Asia/Shanghai
    username: root
    password: 123456

  redis:
    host: 192.168.217.4
    port: 6379
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-wait: -1
        max-active: 20
        max-idle: 5
        min-idle: 0


  #同意返回的json时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai

   #配置nacos
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  #配置项目名称
  application:
    name: service-edu

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml

#开启熔断机制
feign:
  hystrix:
    enabled: true

