server:
  port: 8160

spring:
  application:
    name: service-ucenter
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli?serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  redis:
    host: 192.168.217.4
    port: 6379
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

wx:
  oppen:
    app_id: wxed9954c01bb89b47
    appsecret: a7482517235173ddb4083788de60b90e
    redirecturl: http://localhost:8160/api/ucenter/wx/callback

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml