server:
  port: 8005

spring:
  application:
    name: service-msm
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli?serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  redis:
    host: 192.168.217.4
    port: 6379


#阿里云短信服务配置
aliyun:
  msm:
    file:
      #AccessKeyID
      keyid: LTAI5tMPmnRuSjU3wmEC13TH
      #AccessKey Secret
      keysecret: 60w1Stbt3qSUw6ABilXLeCvSWuFw10
